### ISSUE TITLE
Statement of faith homepage broken link

### ISSUE THREAD

**Issue by JaedanC** [alexreardon/fullon-markdown#21]
`details.md` has a broken link right down the bottom

http://www.matthiasmedia.com.au/2wtl/2wtlonline.html

> This gives us two choices. We can either continue living the way we were, in rejection of God, and face the consequences for our actions, or we can turn and commit our lives to Jesus so that we can return to an eternal relationship with God . [More information](http://www.matthiasmedia.com.au/2wtl/2wtlonline.html)

**Comment by alexreardon** [comment]
PR's welcome! :)

**Comment by JaedanC** [comment]
Actually there's two more

http://en.stphils.org.au/about-us/staff-profiles/

> For questions about camp and registrations contact [Jason Smith](http://en.stphils.org.au/about-us/staff-profiles/) or [Al James](http://en.stphils.org.au/about-us/staff-profiles/).

It should be http://stphils.org.au/staff-team/ maybe. But this is generic across the whole church and may not be what you want.

My dummy head never done a PR before so bear with me while I figure it out.
